# Generated by Django 2.2.12 on 2020-09-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='use_profile',
            new_name='user_profile',
        ),
    ]
