# Generated by Django 2.2.12 on 2020-08-24 09:50

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('sign', models.CharField(default=user.models.default_sign, max_length=50, verbose_name='个人签名')),
                ('info', models.CharField(max_length=150, verbose_name='个人简介')),
                ('avatar', models.ImageField(null=True, upload_to='Avatar')),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
    ]
