# Generated by Django 2.2.12 on 2020-08-28 08:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.CharField(default=user.models.default_info, max_length=150, verbose_name='个人简介'),
        ),
    ]
